#!/bin/sh

notify() {
	gdbus call -e -d "org.freedesktop.Notifications" \
		-o /org/freedesktop/Notifications \
		-m org.freedesktop.Notifications.Notify "" \
		$1 "" "$2" "$3" "[]" "{}" 2000 >/dev/null
}

# find next theme
next_is_new=false
current=$(cat ~/.themes/current)
themes=$(ls -I . -I .. ~/.themes | grep -v current)

for i in $themes; do
	if [ $next_is_new == true ]; then
		new=$i
		break
	fi

	if [ $current == $i ]; then
		next_is_new=true
	fi
done

if [ -z $new ]; then
	for i in $themes; do
		new=$i
		break
	done
fi

# update current
echo $new > ~/.themes/current

# Edit gtk-3.0
sed -i "s/gtk-theme-name=$current/gtk-theme-name=$new/" ~/.config/gtk-3.0/settings.ini

notify 69 "Theme" "$new"
