#!/bin/sh
#
#   ┏━━━━━━━┓
#   ┃ bspwm ┃
#   ┗━━━━━━━┛
#

# wallpaper
hefrandom

bspc monitor -d 1 2 3 4 5 6

bspc config window_gap 10
bspc config border_width 0
#bspc config border_radius 7

# Start mouse
xsetroot -cursor_name left_ptr

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus true

bspc config normal_border_color "#18191c"
bspc config focused_border_color "#c488ec"
bspc config presel_feedback_color "#18191c"

#bspc config normal_frame_opacity 0
#bspc config focused_frame_opacity 0.75

# ============
# Window Rules
# ============

# bspc rule -a Zathura state=tiled
bspc rule -a \* state=tiled
# bspc rule -a pavucontrol-qt state=tiled
# bspc rule -a linthesia state=tiled
bspc rule -a Steam desktop='^6' follow=on
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a discord desktop='^4' follow=on

# ============
# Startup
# ============

# Start key daemon
sxhkd &

# Start compositor
picom &

# Start polybar
rabylop &

# Start polykit gtk
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# notification daemon
dunst &

# launch keyboard controller
fcitx5 -d &

# rename bspwm so java apps works
wmname LG3D

# battyer daemon
battery 300 10