#!/bin/sh


# get current layout
out=$(swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name')
current_layout=${out#*:}

case $current_layout in 
	"\"bu\"")
		notify-send 69 "中文"
		swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 2
        /home/liabri/.cargo/bin/ankrad;;
	"\"fw\"")
		notify-send 69 "bu"
		swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 0
        pkill ankrad;;
	"\"rsc\"")		
		notify-send 69 "bu"
		swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 0
        pkill ankrad;;
esac