#!/bin/sh

# get current layout
out=$(swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name')
current_layout=${out#*:}

case $1 in
	"rs")
		case $current_layout in 
			"\"rsc\"")		
				notify-send 69 "bu"
				swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 0
		        pkill ankrad;;
			*)
				notify-send 69 "rsc"
				swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 1
				pkill ankrad;;
		esac;;
	"zh")
		case $current_layout in 
			"\"fw\"")
				notify-send 69 "bu"
				swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 0
		        pkill ankrad;;
			*)
		        pkill ankrad
				notify-send 69 "中文"
				swaymsg input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout 2
		        /home/liabri/.cargo/bin/ankrad;;
		esac;;
esac