#!/bin/sh
#
#   ┏━━━━━━━┓
#   ┃ bspwm ┃
#   ┗━━━━━━━┛
#

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 10

bspc config window_gap 10
bspc config border_width 0
bspc config border_radius 7

# Start mouse
xsetroot -cursor_name left_ptr

# Set wallpaper
hefrandom

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus true

bspc config normal_border_color "#18191c"
bspc config focused_border_color "#c488ec"
bspc config presel_feedback_color "#18191c"

bspc config normal_frame_opacity 0
bspc config focused_frame_opacity 0.75

# ============
# Window Rules
# ============

bspc rule -a Peek state=floating
bspc rule -a Zathura state=tiled
bspc rule -a cmus desktop='^5'
bspc rule -a clyrics desktop='^5'
bspc rule -a pavucontrol-qt state=tiled

# ============
# Applications
# ============

# Start key daemon
sxhkd &

# Start compositor
compton &

# Start polybar
rabylop &
